spring:
  application:
    name: binddog-hub
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  data:
    mongodb:
      host: ${MONGODB_HOST}
      username: ${MONGODB_USER}
      password: ${MONGODB_PASSWORD}
      database: ${MONGODB_DB}
      authentication-database: ${MONGODB_AUTH_DB}
      port: ${MONGODB_PORT}
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: ${HUB_PORT}
  servlet:
    context-path: /api
  tomcat:
    max-http-form-post-size: 100MB

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret-key: ${JWT_SECRET_KEY}

minio:
  endpoint: ${MINIO_ENDPOINT}      # MinIO 서버 엔드포인트
  access-key: ${MINIO_ACCESS_KEY}                    # MinIO 액세스 키
  secret-key: ${MINIO_SECRET_KEY}                 # MinIO 비밀 키
  bucket-name: ${MINIO_BUCKET_NAME}                # 사용할 버킷 이름
  presigned-url : ${MINIO_PRESIGNED_URL}